### Hello World

GET http://hh-0001.local/

### Hello World HTTPS

# @curl-insecure
GET https://hh-0001.local/

### Get config

GET http://hh-0001.local/config

### Post config

POST http://hh-0001.local/config
Content-Type: text/plain

testremote
