### Hello World

GET http://hh-0001.local/

### Hello World HTTPS

# @curl-insecure
GET https://hh-0001.local/

### Get config

GET http://hh-1001.local/config

### Post config

POST http://hh-1001.local/config
Content-Type: text/plain

my ir remote
irplay:my button,qgoAAE0DAAANAgAALwMAABICAABoAQAAEgIAAG0BAACHBQAA8QQAAPQBAACGAQAAEgIAAG0BAAD0AQAAhgEAAAMCAAB8AQAA-QEAAIYBAAANAgAAbQEAABICAABtAQAAEgIAAG0BAAANAgAAbQEAABICAABtAQAADQIAAG0BAACxAwAAkAEAAPQBAABIAwAA9AEAAIYBAAD5AQAAt0cBAKoKAABNAwAA-QEAAD4DAAD5AQAAhgEAAPkBAACGAQAAbgUAAAUFAAD5AQAAhgEAAPkBAACGAQAA9AEAAIYBAAD0AQAAiwEAAPQBAACLAQAA7wEAAIsBAAD0AQAAiwEAAO8BAACLAQAA9AEAAIsBAADvAQAAkAEAAPQBAACGAQAAsQMAAIsBAAD0AQAASAMAAPQBAACLAQAA1gEAANpHAQCHCgAAawMAANEBAABrAwAA0QEAAK4BAADRAQAArgEAAEsFAAAoBQAA0QEAAK4BAADMAQAArgEAANEBAACuAQAAzAEAALMBAADMAQAArgEAANEBAACuAQAA0QEAAK4BAADMAQAArgEAANEBAACuAQAAzAEAAK4BAADRAQAArgEAAI4DAACuAQAA0QEAAGsDAADqAQAAlQEAAMwBAAAAAAAA

### Click angle

POST http://hh-0001.local/click?angle=121&channel=5&duration=100

### Record

GET http://hh-1001.local/record

### Play

POST http://hh-1001.local/play
Content-Type: text/plain

qgoAAE0DAAANAgAALwMAABICAABoAQAAEgIAAG0BAACHBQAA8QQAAPQBAACGAQAAEgIAAG0BAAD0AQAAhgEAAAMCAAB8AQAA-QEAAIYBAAANAgAAbQEAABICAABtAQAAEgIAAG0BAAANAgAAbQEAABICAABtAQAADQIAAG0BAACxAwAAkAEAAPQBAABIAwAA9AEAAIYBAAD5AQAAt0cBAKoKAABNAwAA-QEAAD4DAAD5AQAAhgEAAPkBAACGAQAAbgUAAAUFAAD5AQAAhgEAAPkBAACGAQAA9AEAAIYBAAD0AQAAiwEAAPQBAACLAQAA7wEAAIsBAAD0AQAAiwEAAO8BAACLAQAA9AEAAIsBAADvAQAAkAEAAPQBAACGAQAAsQMAAIsBAAD0AQAASAMAAPQBAACLAQAA1gEAANpHAQCHCgAAawMAANEBAABrAwAA0QEAAK4BAADRAQAArgEAAEsFAAAoBQAA0QEAAK4BAADMAQAArgEAANEBAACuAQAAzAEAALMBAADMAQAArgEAANEBAACuAQAA0QEAAK4BAADMAQAArgEAANEBAACuAQAAzAEAAK4BAADRAQAArgEAAI4DAACuAQAA0QEAAGsDAADqAQAAlQEAAMwBAAAAAAAA

### teest
